#!/usr/bin/env python3
"""DINO program ROM image generator (AT28C256, 32KB, ROM 0x0000-0x7FFF).

Emits roms/PROG.bin (the real program) + roms/PROG_diag.bin (the
address-proof image), their CRC16s, and the rig's expect header
(tests/dino_bringup/src/progrom_expect.h) so rig and ROM can never
disagree — same contract microcode_gen.py holds for the microcode pair.

OPCODES and instruction LENGTHS are imported from microcode_gen: one
source of truth. The assembler validates every operand count against the
microcode table, so a program can never encode an instruction the
microcode cannot execute.

DIAG image (memory.rom.order): content-addressed and SELF-NAMING —
  addr 0    -> 0xA5 marker
  addr 2^k  -> 0x40|k  (k = 0..14)   <- a mis-decoded address line reports
                                        the address the chip ACTUALLY saw
  else      -> multiplicative hash, so every other row is distinctive too
15 address lines is a lot of one-hole opportunity; this retires the
mirror/swap/stuck class the way the microcode diag burn did.

REAL image: the MILESTONE program (hard gate — the machine adds two
numbers), safe-filled with HALT so an erased or overrun ROM halts
instead of raving.

Run:  python3 progrom_gen.py          (writes roms/ + expect header)
Test: python3 test_progrom_gen.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from microcode_gen import OPCODES, INSTRUCTIONS   # noqa: E402  single source

HERE = os.path.dirname(os.path.abspath(__file__))
ROMS = os.path.normpath(os.path.join(HERE, "..", "..", "roms"))
HDR = os.path.normpath(os.path.join(
    HERE, "..", "..", "tests", "dino_bringup", "src", "progrom_expect.h"))

SIZE = 32768                    # AT28C256, ROM half of the memory map
SAFE_FILL = OPCODES["HALT"]     # erased/overrun ROM must HALT, never rave

# ---- diag image ---------------------------------------------------------
DIAG_ZERO = 0xA5                # address 0 marker (also the burn signature)
DIAG_WALK = 0x40                # 2^k -> DIAG_WALK|k, k = 0..14
WITNESS_ADDRS = [0] + [1 << k for k in range(15)]


def diag_byte(addr):
    """Content-addressed diag value. Self-naming on the witness set."""
    addr &= SIZE - 1
    if addr == 0:
        return DIAG_ZERO
    if addr & (addr - 1) == 0:                  # exact power of two
        return DIAG_WALK | addr.bit_length() - 1
    return ((addr * 0x9D) ^ (addr >> 5)) & 0xFF


def build_diag():
    return bytes(diag_byte(a) for a in range(SIZE))


# ---- the milestone program ---------------------------------------------
# HARD GATE (Rico): no ISA/hardware extensions until the whole machine
# adds two numbers. This is that program — load, add, expose, halt.
ADDEND_A = 5
ADDEND_B = 3
EXPECT_SUM = ADDEND_A + ADDEND_B

PROGRAM = [
    ("LDAI", ADDEND_A),     # A = 5   (also latches TMP_A shadow)
    ("LDBI", ADDEND_B),     # B = 3   (also latches TMP_B shadow)
    ("ADD",),               # A = TMP_A + TMP_B = 8, flags commit
    ("OUT",),               # OUT register <- A, LEDs show 0x08
    ("HALT",),              # park: T-counter frozen, clock still running
]


class BuildError(Exception):
    pass


def assemble(program):
    """Symbolic steps -> bytes. Operand count and range are validated
    against the microcode table's declared instruction length; operands
    are emitted LO then HI (little-endian, 8008 lineage)."""
    out = bytearray()
    for step in program:
        name, operands = step[0], list(step[1:])
        if name not in OPCODES or name not in INSTRUCTIONS:
            raise BuildError(f"unknown mnemonic {name!r}")
        want = INSTRUCTIONS[name][0] - 1        # length includes the opcode
        if len(operands) != want:
            raise BuildError(
                f"{name}: {len(operands)} operands, microcode declares {want}")
        for v in operands:
            if not 0 <= v <= 0xFF:
                raise BuildError(f"{name}: operand {v} out of byte range")
        out.append(OPCODES[name])
        out.extend(operands)
    return bytes(out)


def build_real():
    code = assemble(PROGRAM)
    if len(code) > SIZE:
        raise BuildError("program larger than the ROM")
    if code[0] == DIAG_ZERO:
        raise BuildError("program byte 0 collides with the diag signature")
    return code + bytes([SAFE_FILL]) * (SIZE - len(code))


# ---- CRC-16/CCITT-FALSE (same routine the rig links, src/crc16.c) ------
def crc16(data):
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 \
                else (crc << 1) & 0xFFFF
    return crc


# ---- rig expect header --------------------------------------------------
def emit_header(real, crcs, path):
    code_len = len(assemble(PROGRAM))
    lines = [
        "/* GENERATED by docs/notes/progrom_gen.py — do not edit.",
        "   Regenerate: python3 docs/notes/progrom_gen.py */",
        "#ifndef PROGROM_EXPECT_H",
        "#define PROGROM_EXPECT_H",
        "#ifdef __AVR__",
        "#include <avr/pgmspace.h>",
        "#else",
        "#define PROGMEM",
        "#endif",
        "#include <stdint.h>",
        "",
        f"#define PR_SIZE {SIZE}u",
        f"#define PR_SAFE_FILL 0x{SAFE_FILL:02X}u",
        "",
        "/* burn signatures: byte 0 of each image */",
        f"#define PR_DIAG_BYTE0 0x{build_diag()[0]:02X}u",
        f"#define PR_REAL_BYTE0 0x{real[0]:02X}u",
        "",
        "/* CRC-16/CCITT-FALSE over all 32768 bytes */",
    ]
    for name, val in crcs.items():
        lines.append(f"#define {name} 0x{val:04X}u")
    lines += [
        "",
        f"#define PR_DIAG_ZERO 0x{DIAG_ZERO:02X}u",
        f"#define PR_DIAG_WALK 0x{DIAG_WALK:02X}u",
        "",
        "/* diag value is a pure function of its address — the rig computes",
        "   it rather than carrying a 32KB table. Self-naming on 0 and 2^k. */",
        "static inline uint8_t pr_diag_byte(uint16_t a) {",
        "    a &= (uint16_t)(PR_SIZE - 1u);",
        "    if (a == 0u) return PR_DIAG_ZERO;",
        "    if ((a & (uint16_t)(a - 1u)) == 0u) {",
        "        uint8_t k = 0;",
        "        while ((uint16_t)(a >> k) > 1u) k++;",
        "        return (uint8_t)(PR_DIAG_WALK | k);",
        "    }",
        "    return (uint8_t)(((uint16_t)(a * 0x9Du)) ^ (a >> 5));",
        "}",
        "",
        "/* the shipped program; every address at or past PR_PROGRAM_LEN",
        "   reads PR_SAFE_FILL */",
        f"#define PR_PROGRAM_LEN {code_len}u",
        "static const uint8_t PR_PROGRAM[PR_PROGRAM_LEN] PROGMEM = {",
        "    " + ", ".join(f"0x{b:02X}" for b in real[:code_len]) + ",",
        "};",
        "",
        f"#define PR_EXPECT_SUM 0x{EXPECT_SUM:02X}u   /* the milestone result */",
        "",
        "#endif",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    real, diag = build_real(), build_diag()
    os.makedirs(ROMS, exist_ok=True)
    crcs = {}
    for tag, img, fn in (("REAL", real, "PROG.bin"),
                         ("DIAG", diag, "PROG_diag.bin")):
        with open(os.path.join(ROMS, fn), "wb") as f:
            f.write(img)
        crcs[f"PR_CRC_{tag}"] = crc16(img)
    emit_header(real, crcs, HDR)
    print(f"wrote 2x {SIZE}B bins -> {ROMS}")
    print(f"wrote expect header -> {HDR}")
    print("burn order: DIAG first (rom.order proves 15 address lines),")
    print("            then REAL (the milestone program)")
    print(f"  program: {' '.join(s[0] for s in PROGRAM)}"
          f"  -> OUT should show 0x{EXPECT_SUM:02X}")
    for name, val in crcs.items():
        print(f"  {name} = 0x{val:04X}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
