#!/usr/bin/env python3
"""Host test for kicad_contracts.py --pinmap. Run: python3 test_kicad_contracts_pinmap.py"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "tests", "dino_bringup", "src", "pinmap_gen.h")

subprocess.run([sys.executable, os.path.join(HERE, "kicad_contracts.py"), "--pinmap"],
               check=True, capture_output=True)
t = open(OUT).read()

assert t.splitlines()[0].startswith("/* GENERATED by kicad_contracts.py"), "missing generated marker"
# W bus pinned to PORTA in every module that has it
for m in re.finditer(r'\{"W0",\s*"([^"]+)"', t):
    assert m.group(1).startswith("PA0"), f"W0 must be PA0/D22, got {m.group(1)}"
# MDR bus on PORTF
for m in re.finditer(r'\{"MDR0",\s*"([^"]+)"', t):
    assert m.group(1).startswith("PF0"), f"MDR0 must be PF0/A0, got {m.group(1)}"
# every module block present (sheet names, lowercased tokens)
for mod in ("root", "mar", "memory", "control_word"):
    assert f'"{mod}"' in t, f"module {mod} missing"
# alias-joined bus bits still land on their bus port (Task 3 reads whole ports)
for m in re.finditer(r'\{"([^"]*M15[^"]*)",\s*"([^"]+)"', t):
    assert m.group(2).startswith("PL7"), f"{m.group(1)} must be PL7/D42, got {m.group(2)}"
assert re.search(r'\{"[^"]*M15[^"]*",\s*"PL7', t), "no M15 signal mapped to PL7"
for m in re.finditer(r'\{"([^"]*SA2[^"]*)",\s*"([^"]+)"', t):
    assert m.group(2).startswith("PL1/D48"), f"{m.group(1)} (=CW9) must be PL1/D48, got {m.group(2)}"
# no signal assigned two different pins within one module
for block in re.findall(r'static const sigpin_t sig_\w+\[\] = \{(.*?)\};', t, re.S):
    pins = re.findall(r'\{"([^"]+)",\s*"([^"]+)",\s*\'(\w)\'\}', block)
    seen = {}
    for sig, pin, d in pins:
        assert sig not in seen, f"duplicate signal {sig}"
        seen[sig] = pin
    assert len(set(seen.values())) == len(seen), "pin double-booked in one module"
print("pinmap host test: OK")
