#!/usr/bin/env python3
"""Host test for microcode_gen.py. Run: python3 test_microcode_gen.py

Truth sources: dino_session_state.md (CW bit map, microword table, fill
rules), dino_test_bringup_design.md (diag image spec, per-chip CRCs),
dino_design_notes.md (builder assert list).
"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROMS = os.path.join(HERE, "..", "..", "roms")
HDR = os.path.join(HERE, "..", "..", "tests", "dino_bringup", "src",
                   "microcode_expect.h")

sys.path.insert(0, HERE)
import microcode_gen as g

# ---- CRC16 algorithm (CCITT-FALSE): the one known-answer vector ----
assert g.crc16(b"123456789") == 0x29B1, "crc16 not CRC-16/CCITT-FALSE"

# ---- real image: word-level truth from the session-state table ----
real = g.build_real()
assert len(real) == 4096
# T0 of ALL 256 opcodes = universal fetch (hard rule, session state item 3)
for op in range(256):
    assert real[op * 16 + 0] == 0x600E, f"T0 of opcode {op:#04x} not fetch"
# unused rows = safe-fill END
assert real[0x0F5] == 0x1000, "safe-fill missing (opcode 0x0F, T5)"
assert real[0xE31] == 0x1000, "safe-fill missing (opcode 0xE3, T1)"
# NOP
assert real[g.OPCODES["NOP"] * 16 + 1] == 0x1000
# loads immediate (LDAI anchored at 0x11 by the addressing spec)
assert g.OPCODES["LDAI"] == 0x11, "LDAI must stay 0x11 (doc anchor)"
assert real[0x111] == 0x7009, "LDAI T1"
assert real[g.OPCODES["LDBI"] * 16 + 1] == 0x700A
assert real[g.OPCODES["LDCI"] * 16 + 1] == 0x700B
# memory ops share the T1/T2 MAR-fill prefix
for name in ("LDA", "STA", "JMP", "JNZ"):
    base = g.OPCODES[name] * 16
    assert real[base + 1] == 0x600C, f"{name} T1 (dst=MAR_LO)"
    assert real[base + 2] == 0x600D, f"{name} T2 (dst=MAR_HI)"
assert real[g.OPCODES["LDA"] * 16 + 3] == 0x1011
assert real[g.OPCODES["STA"] * 16 + 3] == 0x101F
assert real[g.OPCODES["JMP"] * 16 + 3] == 0x1080
assert real[g.OPCODES["JNZ"] * 16 + 3] == 0x10C0
# ALU family = 0x1631 with [11:9] per the op code table
alu_want = {"ADD": 0x1631, "SUB": 0x1431, "AND": 0x1C31, "OR": 0x1A31,
            "XOR": 0x1831, "CLR": 0x1031, "SET": 0x1E31, "BSUB": 0x1231}
for name, w in alu_want.items():
    assert real[g.OPCODES[name] * 16 + 1] == w, f"{name} T1"
# OUT
assert real[g.OPCODES["OUT"] * 16 + 1] == 0x1198
# HALT: bit15 only, NO END bit (rule changed 2026-07-14); rest of block fill
assert real[g.OPCODES["HALT"] * 16 + 1] == 0x8000
assert real[g.OPCODES["HALT"] * 16 + 2] == 0x1000

# ---- diag image: word = own addr[11:0] | ~addr[11:8] in [15:12] ----
diag = g.build_diag()
assert len(diag) == 4096
assert diag[0x000] == 0xF000
assert diag[0xFFF] == 0x0FFF
assert diag[0xA5A] == 0x5A5A
assert diag[0x123] == 0xE123
for a in range(4096):
    assert diag[a] == (a | ((~(a >> 8) & 0xF) << 12))

# ---- builder asserts (design-notes list) fire on crafted bad words ----
def must_raise(addr, word, why):
    try:
        g.check_word(addr, word)
    except g.BuildError:
        return
    raise AssertionError(f"check_word accepted {why} ({word:#06x})")

# /MDR_OUT ([8:6]=100) + src!=NONE = two W-bus drivers
must_raise(0x011, 0x1100 | 0x0008, "MDR_OUT plus src=ROM")
# PC_UP together with /PC_LOAD ([8:6]=010)
must_raise(0x011, 0x2080, "PC_UP with PC_LOAD")
# src device == dst device, RAM case
must_raise(0x011, 0x1000 | (0b010 << 3) | 0b111, "src=RAM dst=RAM")
# IR_LOAD (dst=110) outside T0
must_raise(0x011, 0x1006, "IR_LOAD outside T0")
# T0 row that is not the universal fetch
must_raise(0x010, 0x1000, "non-fetch T0 row")
# whole-table check: an opcode block with no END and no HALT runs into fill
bad = list(real)
bad[0x111] = 0x6009            # LDAI T1 with END stripped
try:
    g.check_table(bad)
    raise AssertionError("check_table accepted END-less opcode block")
except g.BuildError:
    pass
g.check_table(real)            # the shipped table must pass its own police

# ---- CLI: bins + header on disk ----
subprocess.run([sys.executable, os.path.join(HERE, "microcode_gen.py")],
               check=True, capture_output=True)
bins = {}
for fn in ("U9.bin", "U15.bin", "U9_diag.bin", "U15_diag.bin"):
    p = os.path.join(ROMS, fn)
    assert os.path.exists(p), f"missing {fn}"
    bins[fn] = open(p, "rb").read()
    assert len(bins[fn]) == 8192, f"{fn} not AT28C64B-sized (8192B)"
    # A12 is grounded on the board: upper half unreachable, mirror it so a
    # floating/mis-tied A12 still reads the same image
    assert bins[fn][:4096] == bins[fn][4096:], f"{fn} upper half not mirrored"

# byte roles: U9 = word[7:0] (CW0-7), U15 = word[15:8] (CW8-15)
for a in (0x000, 0x111, 0xA5A, 0xFFF):
    assert bins["U9.bin"][a] == real[a] & 0xFF
    assert bins["U15.bin"][a] == real[a] >> 8
    assert bins["U9_diag.bin"][a] == diag[a] & 0xFF
    assert bins["U15_diag.bin"][a] == diag[a] >> 8

# ---- expect header consumed by the rig ----
t = open(HDR).read()
assert t.splitlines()[0].startswith("/* GENERATED by microcode_gen.py"), \
    "missing generated marker"
assert "#include <avr/pgmspace.h>" in t

def hdr_val(name):
    m = re.search(rf"#define {name}\s+0x([0-9A-Fa-f]+)", t)
    assert m, f"header missing {name}"
    return int(m.group(1), 16)

# CRCs are computed over the 4096 ADDRESSABLE bytes (what the rig can walk)
assert hdr_val("MC_CRC_U9_REAL") == g.crc16(bins["U9.bin"][:4096])
assert hdr_val("MC_CRC_U15_REAL") == g.crc16(bins["U15.bin"][:4096])
assert hdr_val("MC_CRC_U9_DIAG") == g.crc16(bins["U9_diag.bin"][:4096])
assert hdr_val("MC_CRC_U15_DIAG") == g.crc16(bins["U15_diag.bin"][:4096])
# image-detect signatures
assert hdr_val("MC_REAL_ROW0") == 0x600E
assert hdr_val("MC_DIAG_ROW0") == 0xF000
# full real-word table in flash, for row-naming diagnostics on the bench
m = re.search(r"MC_REAL_WORDS\[4096\] PROGMEM = \{(.*?)\};", t, re.S)
assert m, "header missing MC_REAL_WORDS[4096]"
words = [int(x, 16) for x in re.findall(r"0x[0-9A-Fa-f]{4}", m.group(1))]
assert words == real, "MC_REAL_WORDS drifted from build_real()"

# CLI must PRINT the per-chip CRCs (the bench copies them into the log)
out = subprocess.run([sys.executable, os.path.join(HERE, "microcode_gen.py")],
                     check=True, capture_output=True, text=True).stdout
for name in ("MC_CRC_U9_REAL", "MC_CRC_U15_REAL",
             "MC_CRC_U9_DIAG", "MC_CRC_U15_DIAG"):
    assert f"0x{hdr_val(name):04X}" in out, f"CRC {name} not printed"

print("OK test_microcode_gen")
