#!/usr/bin/env python3
"""Host test for kicad_contracts.py --pinmap. Run: python3 test_kicad_contracts_pinmap.py"""
import os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "tests", "dino_bringup", "src", "pinmap_gen.h")

subprocess.run([sys.executable, os.path.join(HERE, "kicad_contracts.py"), "--pinmap"],
               check=True, capture_output=True)
t = open(OUT).read()

assert t.splitlines()[0].startswith("/* GENERATED by kicad_contracts.py"), "missing generated marker"

# Tables must live in flash: interned PROGMEM strings + PROGMEM struct arrays.
assert "#include <avr/pgmspace.h>" in t, "missing pgmspace include"
strings = dict(re.findall(r'static const char (pm_s\d+)\[\] PROGMEM = "([^"]*)";', t))
assert strings, "no interned PROGMEM strings emitted"

# Resolve each sig_<mod> block back to (signal, pin, dir) tuples.
modules = {}  # tok -> [(sig, pin, dir), ...]
for tok, block in re.findall(r'static const sigpin_t sig_(\w+)\[\] PROGMEM = \{(.*?)\};', t, re.S):
    rows = re.findall(r"\{(pm_s\d+), (pm_s\d+), '(\w)'\}", block)
    assert rows, f"sig_{tok} has no parseable rows"
    modules[tok] = [(strings[s], strings[p], d) for s, p, d in rows]
assert modules, "no sig_<mod> PROGMEM blocks found"

# MODMAPS must be PROGMEM and reference the module name strings + arrays.
mm = re.search(r'static const modmap_t MODMAPS\[\] PROGMEM = \{(.*?)\};', t, re.S)
assert mm, "MODMAPS must be PROGMEM"
mod_names = [strings[s] for s, _tok, _n in
             re.findall(r'\{(pm_s\d+), sig_(\w+), (\d+)\}', mm.group(1))]
for s, tok, n in re.findall(r'\{(pm_s\d+), sig_(\w+), (\d+)\}', mm.group(1)):
    assert strings[s] == tok, f"MODMAPS name {strings[s]} != array token {tok}"
    assert int(n) == len(modules[tok]), f"MODMAPS count mismatch for {tok}"

# W bus pinned to PORTA in every module that has it
for tok, rows in modules.items():
    for sig, pin, _d in rows:
        if sig == "W0":
            assert pin.startswith("PA0"), f"W0 must be PA0/D22, got {pin} in {tok}"
        # MDR bus on PORTF
        if sig == "MDR0":
            assert pin.startswith("PF0"), f"MDR0 must be PF0/A0, got {pin} in {tok}"
        # alias-joined bus bits still land on their bus port (Task 3 reads whole ports)
        if "M15" in sig:
            assert pin.startswith("PL7"), f"{sig} must be PL7/D42, got {pin} in {tok}"
        if "SA2" in sig:
            assert pin.startswith("PL1/D48"), f"{sig} (=CW9) must be PL1/D48, got {pin} in {tok}"
assert any("M15" in sig for rows in modules.values() for sig, _p, _d in rows), \
    "no M15 signal mapped"

# every module block present (sheet names, lowercased tokens)
for mod in ("root", "mar", "memory", "control_word"):
    assert mod in mod_names, f"module {mod} missing"

# no signal assigned two different pins within one module
for tok, rows in modules.items():
    seen = {}
    for sig, pin, _d in rows:
        assert sig not in seen, f"duplicate signal {sig} in {tok}"
        seen[sig] = pin
    assert len(set(seen.values())) == len(seen), f"pin double-booked in {tok}"
print("pinmap host test: OK")
