/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32l4xx.h"
#include <stdint.h>
#include <stdio.h>
#include "FreeRTOS.h"
#include "task.h"

/* Global variables to manipulate in the task */
volatile uint32_t debug_marker = 0;
volatile uint32_t gpioenreg = 0;
void TestTask(void *params)

{
  while (1)
  {
    debug_marker = 0xDEADBEEF;
    gpioenreg = 0xCAFEBABE;
    vTaskDelay(pdMS_TO_TICKS(1000)); // Delay 1 second
  }
}

int main(void)
{
  BaseType_t result = xTaskCreate(TestTask, "Test", 128, NULL, 1, NULL);
  if (result != pdPASS)
  {
    debug_marker = 0xBAADF00D; // failed to create task
  }

  vTaskStartScheduler();

  // fallback trap if scheduler fails
  debug_marker = 0xDEADC0DE;
  while (1)
    ; // scheduler never returned? bad.
}