<?php
$phrases = [
"The Hobbit\n\nJ.R.R Tolkien",
"Three Novels\n\nJack London",
"1984\n\nGeorge Orwell",
"To Kill a Mockingbird\n\nHarper Lee",
"Pride and Prejudice\n\nJane Austen",
"The Great Gatsby\n\nF. Scott Fitzgerald",
"Moby Dick\n\nHerman Melville",
"War and Peace\n\nLeo Tolstoy",
"Crime and Punishment\n\nFyodor Dostoevsky",
"The Catcher in the Rye\n\nJ.D. Salinger",
"Brave New World\n\nAldous Huxley",
"Jane Eyre\n\nCharlotte Brontë",
"Wuthering Heights\n\nEmily Brontë",
"Anna Karenina\n\nLeo Tolstoy",
"The Odyssey\n\nHomer",
"The Iliad\n\nHomer",
"Les Misérables\n\nVictor Hugo",
"The Count of Monte Cristo\n\nAlexandre Dumas",
"Don Quixote\n\nMiguel de Cervantes",
"Ulysses\n\nJames Joyce",
"The Divine Comedy\n\nDante Alighieri",
"Frankenstein\n\nMary Shelley",
"Dracula\n\nBram Stoker",
"The Picture of Dorian Gray\n\nOscar Wilde",
"Great Expectations\n\nCharles Dickens",
"A Tale of Two Cities\n\nCharles Dickens",
"David Copperfield\n\nCharles Dickens",
"Oliver Twist\n\nCharles Dickens",
"Bleak House\n\nCharles Dickens",
"Middlemarch\n\nGeorge Eliot",
"Silas Marner\n\nGeorge Eliot",
"The Mill on the Floss\n\nGeorge Eliot",
"Madame Bovary\n\nGustave Flaubert",
"The Brothers Karamazov\n\nFyodor Dostoevsky",
"Notes from Underground\n\nFyodor Dostoevsky",
"The Idiot\n\nFyodor Dostoevsky",
"Demons\n\nFyodor Dostoevsky",
"The Scarlet Letter\n\nNathaniel Hawthorne",
"The House of the Seven Gables\n\nNathaniel Hawthorne",
"Walden\n\nHenry David Thoreau",
"Leaves of Grass\n\nWalt Whitman",
"The Adventures of Huckleberry Finn\n\nMark Twain",
"The Adventures of Tom Sawyer\n\nMark Twain",
"A Connecticut Yankee in King Arthur's Court\n\nMark Twain",
"The Prince and the Pauper\n\nMark Twain",
"Uncle Tom's Cabin\n\nHarriet Beecher Stowe",
"The Jungle\n\nUpton Sinclair",
"The Grapes of Wrath\n\nJohn Steinbeck",
"Of Mice and Men\n\nJohn Steinbeck",
"East of Eden\n\nJohn Steinbeck",
"The Pearl\n\nJohn Steinbeck",
"The Old Man and the Sea\n\nErnest Hemingway",
"A Farewell to Arms\n\nErnest Hemingway",
"For Whom the Bell Tolls\n\nErnest Hemingway",
"The Sun Also Rises\n\nErnest Hemingway",
"In Our Time\n\nErnest Hemingway",
"The Sound and the Fury\n\nWilliam Faulkner",
"As I Lay Dying\n\nWilliam Faulkner",
"Light in August\n\nWilliam Faulkner",
"Absalom, Absalom!\n\nWilliam Faulkner",
"Go Down, Moses\n\nWilliam Faulkner",
"Beloved\n\nToni Morrison",
"Song of Solomon\n\nToni Morrison",
"The Bluest Eye\n\nToni Morrison",
"Sula\n\nToni Morrison",
"Tar Baby\n\nToni Morrison",
"One Hundred Years of Solitude\n\nGabriel García Márquez",
"Love in the Time of Cholera\n\nGabriel García Márquez",
"Chronicle of a Death Foretold\n\nGabriel García Márquez",
"Autumn of the Patriarch\n\nGabriel García Márquez",
"Leaf Storm\n\nGabriel García Márquez",
"The Stranger\n\nAlbert Camus",
"The Plague\n\nAlbert Camus",
"The Fall\n\nAlbert Camus",
"The Myth of Sisyphus\n\nAlbert Camus",
"Exile and the Kingdom\n\nAlbert Camus",
"The Trial\n\nFranz Kafka",
"The Metamorphosis\n\nFranz Kafka",
"The Castle\n\nFranz Kafka",
"Amerika\n\nFranz Kafka",
"In the Penal Colony\n\nFranz Kafka",
"The Bell Jar\n\nSylvia Plath",
"Ariel\n\nSylvia Plath",
"Crossing the Water\n\nSylvia Plath",
"Winter Trees\n\nSylvia Plath",
"Johnny Panic and the Bible of Dreams\n\nSylvia Plath",
"The Road\n\nCormac McCarthy",
"No Country for Old Men\n\nCormac McCarthy",
"Blood Meridian\n\nCormac McCarthy",
"The Border Trilogy\n\nCormac McCarthy",
"The Orchard Keeper\n\nCormac McCarthy",
"The Handmaid's Tale\n\nMargaret Atwood",
"Oryx and Crake\n\nMargaret Atwood",
"The Year of the Flood\n\nMargaret Atwood",
"MaddAddam\n\nMargaret Atwood",
"Alias Grace\n\nMargaret Atwood",
"Life of Pi\n\nYann Martel",
"The Kite Runner\n\nKhaled Hosseini",
"A Thousand Splendid Suns\n\nKhaled Hosseini",
"And the Mountains Echoed\n\nKhaled Hosseini",
"The Alchemist\n\nPaulo Coelho",
"Veronika Decides to Die\n\nPaulo Coelho",
"Brida\n\nPaulo Coelho",
"The Valkyries\n\nPaulo Coelho",
"The Devil and Miss Prym\n\nPaulo Coelho",
"The Book Thief\n\nMarkus Zusak",
"I Am the Messenger\n\nMarkus Zusak",
"Bridge of Clay\n\nMarkus Zusak",
"The Underdog\n\nMarkus Zusak",
"Fighting Ruben Wolfe\n\nMarkus Zusak",
"Harry Potter and the Sorcerer's Stone\n\nJ.K. Rowling",
"Harry Potter and the Chamber of Secrets\n\nJ.K. Rowling",
"Harry Potter and the Prisoner of Azkaban\n\nJ.K. Rowling",
"Harry Potter and the Goblet of Fire\n\nJ.K. Rowling",
"Harry Potter and the Order of the Phoenix\n\nJ.K. Rowling",
"Harry Potter and the Half-Blood Prince\n\nJ.K. Rowling",
"Harry Potter and the Deathly Hallows\n\nJ.K. Rowling",
"The Hunger Games\n\nSuzanne Collins",
"Catching Fire\n\nSuzanne Collins",
"Mockingjay\n\nSuzanne Collins",
"Divergent\n\nVeronica Roth",
"Insurgent\n\nVeronica Roth",
"Allegiant\n\nVeronica Roth",
"Four\n\nVeronica Roth",
"The Maze Runner\n\nJames Dashner",
"The Scorch Trials\n\nJames Dashner",
"The Death Cure\n\nJames Dashner",
"The Kill Order\n\nJames Dashner",
"The Fever Code\n\nJames Dashner",
"Percy Jackson and the Olympians: The Lightning Thief\n\nRick Riordan",
"Percy Jackson and the Olympians: The Sea of Monsters\n\nRick Riordan",
"Percy Jackson and the Olympians: The Titan's Curse\n\nRick Riordan",
"Percy Jackson and the Olympians: The Battle of the Labyrinth\n\nRick Riordan",
"Percy Jackson and the Olympians: The Last Olympian\n\nRick Riordan",
"The Heroes of Olympus: The Lost Hero\n\nRick Riordan",
"The Heroes of Olympus: The Son of Neptune\n\nRick Riordan",
"The Heroes of Olympus: The Mark of Athena\n\nRick Riordan",
"The Heroes of Olympus: The House of Hades\n\nRick Riordan",
"The Heroes of Olympus: The Blood of Olympus\n\nRick Riordan",
"The Trials of Apollo: The Hidden Oracle\n\nRick Riordan",
"The Trials of Apollo: The Dark Prophecy\n\nRick Riordan",
"The Trials of Apollo: The Burning Maze\n\nRick Riordan",
"The Trials of Apollo: The Tyrant's Tomb\n\nRick Riordan",
"The Trials of Apollo: The Tower of Nero\n\nRick Riordan",
"Magnus Chase and the Gods of Asgard: The Sword of Summer\n\nRick Riordan",
"Magnus Chase and the Gods of Asgard: The Hammer of Thor\n\nRick Riordan",
"Magnus Chase and the Gods of Asgard: The Ship of the Dead\n\nRick Riordan",
"The Kane Chronicles: The Red Pyramid\n\nRick Riordan",
"The Kane Chronicles: The Throne of Fire\n\nRick Riordan",
"The Kane Chronicles: The Serpent's Shadow\n\nRick Riordan",
];
header('Content-Type: application/json');
echo json_encode(['note' => $phrases[array_rand($phrases)]]);