/*
 * REGISTER MODULE TEST (74LS373 + 74LS245 + 74LS121)
 * ===================================================
 * 
 * PURPOSE:
 * Tests a register module that uses:
 * - 74LS245: Bus transceiver for bidirectional data transfer
 * - 74LS373: Octal latch for data storage
 * - 74LS121: Monostable multivibrator for generating latch pulse
 * - Additional logic gates (NAND, NOR, Inverter) for control (not directly tested)
 * 
 * THEORY OF OPERATION:
 * This module represents a general-purpose register in the CPU. The key innovation
 * is that the latch pulse is generated by discrete logic (74LS121) rather than
 * software timing. This ensures consistent, hardware-controlled timing.
 * 
 * CONTROL SIGNALS:
 * - PULSE_REQ: Triggers the 121 to generate a latch pulse
 * - REG_LOAD: Controls data direction (load from bus vs output to bus)
 * - REG_OUT: Enables register output to bus
 * 
 * TIMING PHASES:
 * T0: Load data to bus with PULSE_REQ to latch into register
 * T1: Read data back from register (REG_OUT active)
 * 
 * CRITICAL WIRING TABLE:
 * ====================================================================================
 * Arduino Pin | Signal Name | Function
 * ------------|-------------|------------------------------------------------------
 * D1 (PD1)    | PULSE_REQ   | Triggers 121 to generate latch pulse
 * D4 (PD4)    | REG_LOAD    | Controls 245 direction (HIGH=A->B write, LOW=B->A read)
 * D5 (PD5)    | REG_OUT     | Enables register output (active LOW)
 * D6-D13      | Data Bus    | 8-bit data (reversed: D13=bit0, D6=bit7)
 * ====================================================================================
 * 
 * 74LS245 CONNECTIONS:
 * ====================================================================================
 * 245 Pin | Connection     | Purpose
 * --------|----------------|--------------------------------------------------
 * 1       | REG_LOAD (D4)  | DIR - Direction control
 * 19      | REG_OUT (D5)   | ~OE - Output Enable (active LOW)
 * 2-9     | Arduino D6-D13 | A0-A7 - A-side (Arduino side)
 * 11-18   | 373 D inputs   | B0-B7 - B-side (Register side)
 * 10      | GND            | Ground
 * 20      | 5V             | VCC
 * ====================================================================================
 * 
 * 74LS373 CONNECTIONS:
 * ====================================================================================
 * 373 Pin | Connection     | Purpose
 * --------|----------------|--------------------------------------------------
 * 11      | 121 Output     | LE - Latch Enable (pulse from 121)
 * 1       | Logic Gates    | ~OE - Output Enable (controlled by logic)
 * 3,4,7,8,13,14,17,18 | 245 B-side | D0-D7 - Data inputs
 * 2,5,6,9,12,15,16,19 | 245 B-side | Q0-Q7 - Data outputs (same nets)
 * 10      | GND            | Ground
 * 20      | 5V             | VCC
 * ====================================================================================
 * 
 * 74LS121 CONNECTIONS:
 * ====================================================================================
 * 121 Pin | Connection     | Purpose
 * --------|----------------|--------------------------------------------------
 * 3       | PULSE_REQ (D1) | A1 - Trigger input (rising edge)
 * 4       | 5V             | A2 - Tied HIGH
 * 5       | GND            | B - Tied LOW for positive edge trigger
 * 6       | Output to 373  | Q - Pulse output to 373 LE
 * 10,11   | RC Network     | Timing components (sets pulse width)
 * 7       | GND            | Ground
 * 14      | 5V             | VCC
 * ====================================================================================
 * 
 * PULSE TIMING:
 * The 121 generates a pulse width determined by the RC network.
 * Typical values: R=10kΩ, C=100pF gives ~1µs pulse
 * This is plenty for the 373's ~30ns hold time requirement
 */

#include "test_register.h"
#include "test_common.h"
#include <avr/io.h>
#include <util/delay.h>
#include <stdbool.h>

// Control signal definitions
#define PULSE_REQ       PD1  // D1 -> Triggers 121 pulse generator
#define REG_LOAD        PD4  // D4 -> 245 DIR (HIGH=write to reg, LOW=read from reg)
#define REG_OUT         PD5  // D5 -> 245 ~OE (LOW=enabled)

// Timing parameters
#define SETUP_TIME       5    // Time for signals to settle
#define PULSE_WAIT      10    // Time to wait after triggering pulse
#define PROPAGATION_TIME 5    // Time for data to propagate through ICs

// Test patterns - same comprehensive set as other tests
static const uint8_t test_patterns[] = {
    0x00,   // All zeros
    0xFF,   // All ones
    0xAA,   // Alternating 10101010
    0x55,   // Alternating 01010101
    0x0F,   // Lower nibble
    0xF0,   // Upper nibble
    0x81,   // Edge bits
    0x42,   // Specific pattern
    0x3C,   // Center block
    0xC3,   // Inverted center
    // Walking ones
    0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,
    // Walking zeros
    0xFE, 0xFD, 0xFB, 0xF7, 0xEF, 0xDF, 0xBF, 0x7F
};

/*
 * init_pins() - Initialize for safe operation
 * 
 * Initial state:
 * - PULSE_REQ LOW (no pulse)
 * - REG_LOAD LOW (read mode)
 * - REG_OUT HIGH (245 disabled)
 * - Data bus high-Z
 */
static void init_pins(void) {
    // Initialize LEDs using common function
    init_leds();
    
    // Configure control pins as outputs
    DDRD |= (1 << PULSE_REQ) | (1 << REG_LOAD) | (1 << REG_OUT);
    
    // Safe initial state
    PORTD &= ~(1 << PULSE_REQ);   // No pulse request
    PORTD &= ~(1 << REG_LOAD);    // 245 in read mode (B->A)
    PORTD |= (1 << REG_OUT);      // 245 disabled (~OE HIGH)
    
    // Data bus as inputs (high-Z)
    DDRD &= ~((1 << PD6) | (1 << PD7));
    DDRB &= ~0x3F;
    PORTD &= ~((1 << PD6) | (1 << PD7));
    PORTB &= ~0x3F;
}

static void set_bus_as_output(void) {
    DDRD |= (1 << PD6) | (1 << PD7);
    DDRB |= 0x3F;
}

static void set_bus_as_input(void) {
    DDRD &= ~((1 << PD6) | (1 << PD7));
    DDRB &= ~0x3F;
    PORTD &= ~((1 << PD6) | (1 << PD7));
    PORTB &= ~0x3F;
}

static void set_bus_as_input_with_pullups(void) {
    DDRD &= ~((1 << PD6) | (1 << PD7));
    DDRB &= ~0x3F;
    PORTD |= (1 << PD6) | (1 << PD7);
    PORTB |= 0x3F;
}

/*
 * write_to_bus() - Write with reversed bit mapping
 * D13=bit0, D6=bit7 (same as all other tests)
 */
static void write_to_bus(uint8_t data) {
    uint8_t portb_value = PORTB & 0xC0;
    for (int i = 0; i < 6; i++) {
        if (data & (1 << i)) {
            portb_value |= (1 << (5 - i));
        }
    }
    PORTB = portb_value;
    
    if (data & 0x40) PORTD |= (1 << PD7); else PORTD &= ~(1 << PD7);
    if (data & 0x80) PORTD |= (1 << PD6); else PORTD &= ~(1 << PD6);
}

/*
 * read_from_bus() - Read with reversed bit mapping
 */
static uint8_t read_from_bus(void) {
    uint8_t result = 0;
    
    for (int i = 0; i < 6; i++) {
        if (PINB & (1 << (5 - i))) {
            result |= (1 << i);
        }
    }
    
    if (PIND & (1 << PD7)) result |= 0x40;
    if (PIND & (1 << PD6)) result |= 0x80;
    
    return result;
}

/*
 * trigger_latch_pulse() - Request 121 to generate latch pulse
 * 
 * The 121 triggers on rising edge of PULSE_REQ and generates
 * a fixed-width pulse determined by its RC network.
 */
static void trigger_latch_pulse(void) {
    PORTD &= ~(1 << PULSE_REQ);   // Ensure LOW
    _delay_us(1);
    PORTD |= (1 << PULSE_REQ);     // Rising edge triggers 121
    _delay_us(PULSE_WAIT);         // Wait for pulse to complete
    PORTD &= ~(1 << PULSE_REQ);   // Return to LOW
}

/*
 * test_register_pattern() - Test one pattern through the register
 * 
 * SEQUENCE:
 * 1. T0 - WRITE PHASE:
 *    - Set REG_LOAD HIGH (245 direction A->B)
 *    - Enable 245 (~OE LOW)
 *    - Arduino writes pattern to bus
 *    - Trigger 121 pulse to latch data
 *    - Disable 245
 * 
 * 2. T1 - READ PHASE:
 *    - Set REG_LOAD LOW (245 direction B->A)
 *    - Enable 245 (~OE LOW)
 *    - Read latched data from register
 *    - Check for floating pins with pull-ups
 */
static bool test_register_pattern(uint8_t pattern) {
    // === T0: WRITE PHASE ===
    // Configure for write (Arduino -> Register)
    PORTD |= (1 << REG_LOAD);     // 245 DIR HIGH (A->B write mode)
    PORTD &= ~(1 << REG_OUT);     // 245 ~OE LOW (enable)
    _delay_us(SETUP_TIME);
    
    // Write pattern to bus
    set_bus_as_output();
    write_to_bus(pattern);
    _delay_us(SETUP_TIME);
    
    // Trigger latch pulse from 121
    trigger_latch_pulse();
    
    // Disable 245 and release bus
    PORTD |= (1 << REG_OUT);      // 245 ~OE HIGH (disable)
    set_bus_as_input();
    _delay_us(SETUP_TIME);
    
    // === T1: READ PHASE ===
    // Configure for read (Register -> Arduino)
    PORTD &= ~(1 << REG_LOAD);    // 245 DIR LOW (B->A read mode)
    PORTD &= ~(1 << REG_OUT);     // 245 ~OE LOW (enable)
    _delay_us(PROPAGATION_TIME);
    
    // Read the latched value
    uint8_t read_value = read_from_bus();
    
    // Check for floating pins
    set_bus_as_input_with_pullups();
    _delay_us(50);
    uint8_t pullup_value = read_from_bus();
    
    // Disable 245
    PORTD |= (1 << REG_OUT);      // 245 ~OE HIGH (disable)
    set_bus_as_input();
    
    // Verify no floating pins and correct value
    bool floating_detected = (read_value != pullup_value);
    return (read_value == pattern) && !floating_detected;
}

/*
 * test_register_run() - Main test entry point
 * 
 * Tests the register module with hardware-generated latch pulses.
 * The 74LS121 ensures consistent timing regardless of software variations.
 * 
 * LED INDICATORS:
 * - Startup sequence: Yellow-Green-Red-Green-Yellow
 * - Yellow solid: Tests running
 * - Green solid: All patterns passed
 * - Red solid: One or more patterns failed
 */
void test_register_run(void) {
    init_pins();
    
    // Show startup sequence
    show_startup_sequence();
    
    // Start test execution (adds 500ms delay)
    start_test_execution();
    
    // Test all patterns
    bool all_passed = true;
    uint8_t num_patterns = sizeof(test_patterns) / sizeof(test_patterns[0]);
    
    for (uint8_t i = 0; i < num_patterns; i++) {
        if (!test_register_pattern(test_patterns[i])) {
            all_passed = false;
            // Continue testing all patterns to identify which fail
        }
        _delay_ms(10);  // Small delay between patterns
    }
    
    // Show final result
    show_test_result(all_passed);
    
    // Halt
    while (1) {
        _delay_ms(100);
    }
}