/*
 * REGISTER MODULE TEST (74LS373 + 74LS245 + 74LS121)
 * ===================================================
 * 
 * PURPOSE:
 * Tests a register module that uses:
 * - 74LS245: Bus transceiver for bidirectional data transfer
 * - 74LS373: Octal latch for data storage
 * - 74LS121: Monostable multivibrator for generating latch pulse
 * - Additional logic gates (NAND, NOR, Inverter) for control (not directly tested)
 * 
 * THEORY OF OPERATION:
 * This module represents a general-purpose register in the CPU. The key innovation
 * is that the latch pulse is generated by discrete logic (74LS121) rather than
 * software timing. This ensures consistent, hardware-controlled timing.
 * 
 * CONTROL WORD (3 bits output simultaneously):
 * The Arduino outputs a 3-bit control word. The 121 monitors these signals
 * and generates a latch pulse when they change to a LOAD state.
 * 
 * D1:D4:D5 Control States:
 * - [0,0,0]: Idle state, 245 disabled
 * - [1,1,0]: Load data into register (121 auto-generates pulse)
 * - [0,0,1]: Read data from register
 * - [1,0,0]: Reserved/unused
 * - [0,1,0]: Reserved/unused
 * 
 * HARDWARE GATE LOGIC (automatic):
 * - 121 triggers on control word transition to LOAD state
 * - 245 ~OE = !(D4 | D5)  [NOR gate - enabled when either HIGH]
 * - 245 DIR = !D5         [Inverter - HIGH for write, LOW for read]
 * - 373 ~OE = D5          [Direct - enabled when D5 is LOW]
 * 
 * CRITICAL WIRING TABLE:
 * ====================================================================================
 * Arduino Pin | Signal     | Function
 * ------------|------------|-------------------------------------------------------
 * D1 (PD1)    | CTRL_BIT0  | Control word bit 0 (part of LOAD trigger)
 * D4 (PD4)    | CTRL_BIT1  | Control word bit 1 (REG_LOAD signal)
 * D5 (PD5)    | CTRL_BIT2  | Control word bit 2 (REG_OUT signal)
 * D6-D13      | Data Bus   | 8-bit data (reversed: D13=bit0, D6=bit7)
 * ====================================================================================
 * 
 * 121 TRIGGER LOGIC:
 * The 121 monitors D1 & D4 and triggers a pulse when transitioning to [1,1,x]
 * This provides automatic latching when LOAD operation is selected.
 * 
 * GATE-CONTROLLED SIGNALS:
 * - 245 pin 19 (~OE) = Output of NOR(D4, D5)
 * - 245 pin 1 (DIR) = Output of NOT(D5)
 * - 373 pin 1 (~OE) = D5 (when LOW, 373 outputs enabled)
 * 
 * 74LS245 CONNECTIONS:
 * ====================================================================================
 * 245 Pin | Connection     | Purpose
 * --------|----------------|--------------------------------------------------
 * 1       | REG_LOAD (D4)  | DIR - Direction control
 * 19      | REG_OUT (D5)   | ~OE - Output Enable (active LOW)
 * 2-9     | Arduino D6-D13 | A0-A7 - A-side (Arduino side)
 * 11-18   | 373 D inputs   | B0-B7 - B-side (Register side)
 * 10      | GND            | Ground
 * 20      | 5V             | VCC
 * ====================================================================================
 * 
 * 74LS373 CONNECTIONS:
 * ====================================================================================
 * 373 Pin | Connection     | Purpose
 * --------|----------------|--------------------------------------------------
 * 11      | 121 Output     | LE - Latch Enable (pulse from 121)
 * 1       | Logic Gates    | ~OE - Output Enable (controlled by logic)
 * 3,4,7,8,13,14,17,18 | 245 B-side | D0-D7 - Data inputs
 * 2,5,6,9,12,15,16,19 | 245 B-side | Q0-Q7 - Data outputs (same nets)
 * 10      | GND            | Ground
 * 20      | 5V             | VCC
 * ====================================================================================
 * 
 * 74LS121 CONNECTIONS:
 * ====================================================================================
 * 121 Pin | Connection     | Purpose
 * --------|----------------|--------------------------------------------------
 * 3       | PULSE_REQ (D1) | A1 - Trigger input (rising edge)
 * 4       | 5V             | A2 - Tied HIGH
 * 5       | GND            | B - Tied LOW for positive edge trigger
 * 6       | Output to 373  | Q - Pulse output to 373 LE
 * 10,11   | RC Network     | Timing components (sets pulse width)
 * 7       | GND            | Ground
 * 14      | 5V             | VCC
 * ====================================================================================
 * 
 * PULSE TIMING:
 * The 121 generates a pulse width determined by the RC network.
 * Typical values: R=10kΩ, C=100pF gives ~1µs pulse
 * This is plenty for the 373's ~30ns hold time requirement
 */

#include "test_register.h"
#include "test_common.h"
#include <avr/io.h>
#include <util/delay.h>
#include <stdbool.h>

// Control signal definitions (3-bit control word)
#define CTRL_BIT0       PD1  // D1 -> Control word bit 0
#define CTRL_BIT1       PD4  // D4 -> Control word bit 1 (LOAD)
#define CTRL_BIT2       PD5  // D5 -> Control word bit 2 (OUT)

// Control word masks for readability
#define CTRL_IDLE       0x00  // [0,0,0] - All disabled
#define CTRL_LOAD       0x03  // [1,1,0] - Load data (D1=1, D4=1, D5=0)
#define CTRL_READ       0x04  // [0,0,1] - Read data (D1=0, D4=0, D5=1)

// Timing parameters
#define SETUP_TIME       5    // Time for signals to settle
#define PULSE_WAIT      10    // Time to wait after triggering pulse
#define PROPAGATION_TIME 5    // Time for data to propagate through ICs

// Test patterns - same comprehensive set as other tests
static const uint8_t test_patterns[] = {
    0x00,   // All zeros
    0xFF,   // All ones
    0xAA,   // Alternating 10101010
    0x55,   // Alternating 01010101
    0x0F,   // Lower nibble
    0xF0,   // Upper nibble
    0x81,   // Edge bits
    0x42,   // Specific pattern
    0x3C,   // Center block
    0xC3,   // Inverted center
    // Walking ones
    0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80,
    // Walking zeros
    0xFE, 0xFD, 0xFB, 0xF7, 0xEF, 0xDF, 0xBF, 0x7F
};

/*
 * init_pins() - Initialize for safe operation
 * 
 * Initial state:
 * - Control word = [0,0,0] (idle)
 * - This makes 245 disabled via NOR gate
 * - Data bus high-Z
 */
static void init_pins(void) {
    // Initialize LEDs using common function
    init_leds();
    
    // Configure control pins as outputs
    DDRD |= (1 << CTRL_BIT0) | (1 << CTRL_BIT1) | (1 << CTRL_BIT2);
    
    // Safe initial state - control word = IDLE [0,0,0]
    // This disables 245 via the NOR gate (!(0|0) = 1 = disabled)
    PORTD &= ~((1 << CTRL_BIT0) | (1 << CTRL_BIT1) | (1 << CTRL_BIT2));
    
    // Data bus as inputs (high-Z)
    set_bus_as_input();
}

// Bus operations are now provided by test_common.h

/*
 * set_control_word() - Output 3-bit control word
 * 
 * The 121 monitors the control bits and automatically generates
 * a latch pulse when transitioning to a LOAD state.
 */
static void set_control_word(uint8_t control) {
    // Clear all control bits first
    PORTD &= ~((1 << CTRL_BIT0) | (1 << CTRL_BIT1) | (1 << CTRL_BIT2));
    
    // Set new control word
    if (control & 0x01) PORTD |= (1 << CTRL_BIT0);  // D1
    if (control & 0x02) PORTD |= (1 << CTRL_BIT1);  // D4
    if (control & 0x04) PORTD |= (1 << CTRL_BIT2);  // D5
    
    // Give hardware time to respond
    _delay_us(PULSE_WAIT);
}

/*
 * test_register_pattern() - Test one pattern through the register
 * 
 * Simply outputs control words - hardware handles everything:
 * - [1,1,0]: Load data (121 auto-generates latch pulse)
 * - [0,0,1]: Read data back
 * - [0,0,0]: Idle between operations
 */
static bool test_register_pattern(uint8_t pattern) {
    // === START IN IDLE STATE ===
    set_control_word(CTRL_IDLE);  // [0,0,0]
    set_bus_as_input();
    _delay_us(SETUP_TIME);
    
    // === LOAD PHASE ===
    // Put data on bus, then set control word to LOAD
    // The 121 will detect the transition and generate a latch pulse
    set_bus_as_output();
    write_to_bus(pattern);
    _delay_us(SETUP_TIME);
    
    set_control_word(CTRL_LOAD);  // [1,1,0] - 121 triggers pulse automatically
    
    // Return to idle
    set_control_word(CTRL_IDLE);  // [0,0,0]
    set_bus_as_input();
    _delay_us(SETUP_TIME);
    
    // === READ PHASE ===
    // Set control word to READ - hardware enables everything correctly
    set_control_word(CTRL_READ);  // [0,0,1]
    _delay_us(PROPAGATION_TIME);
    
    // Read the latched value
    uint8_t read_value = read_from_bus();
    
    // Check for floating pins
    set_bus_as_input_with_pullups();
    _delay_us(50);
    uint8_t pullup_value = read_from_bus();
    
    // Return to idle
    set_control_word(CTRL_IDLE);  // [0,0,0]
    set_bus_as_input();
    
    // Verify no floating pins and correct value
    bool floating_detected = (read_value != pullup_value);
    return (read_value == pattern) && !floating_detected;
}

/*
 * test_register_run() - Main test entry point
 * 
 * Tests the register module with hardware-generated latch pulses.
 * The 74LS121 ensures consistent timing regardless of software variations.
 * 
 * LED INDICATORS:
 * - Startup sequence: Yellow-Green-Red-Green-Yellow
 * - Yellow solid: Tests running
 * - Green solid: All patterns passed
 * - Red solid: One or more patterns failed
 */
void test_register_run(void) {
    init_pins();
    
    // Show startup sequence
    show_startup_sequence();
    
    // Start test execution (adds 500ms delay)
    start_test_execution();
    
    // Test all patterns
    bool all_passed = true;
    uint8_t num_patterns = sizeof(test_patterns) / sizeof(test_patterns[0]);
    
    for (uint8_t i = 0; i < num_patterns; i++) {
        if (!test_register_pattern(test_patterns[i])) {
            all_passed = false;
            // Continue testing all patterns to identify which fail
        }
        _delay_ms(10);  // Small delay between patterns
    }
    
    // Show final result
    show_test_result(all_passed);
    
    // Halt
    while (1) {
        _delay_ms(100);
    }
}