#ifndef HARNESS_H
#define HARNESS_H
#include <stdbool.h>
#include <stdint.h>
#include <avr/pgmspace.h>

typedef struct { volatile uint8_t *port, *ddr, *pinr; uint8_t bit; } hwpin_t;

/* RAM discipline (the 8KB is the rig's scarcest resource): every string
   the firmware only ever PRINTS lives in flash. Test labels and
   signal-name tables are PROGMEM; name tables are arrays of flash
   pointers themselves stored in flash — index them with PN(). The _r
   check variants below exist ONLY for labels built at runtime in RAM
   (selftest's pin names). */
#define PN(tbl, i) ((const char *)pgm_read_word(&(tbl)[i]))

/* Scratch arena, one user at a time (root's burst capture today).
   Future modules needing bulk capture borrow this instead of adding
   their own static buffers. */
#define ARENA_SIZE 2048
extern uint8_t g_arena[ARENA_SIZE];

bool pin_lookup(const char *megapin, hwpin_t *out);
bool sig_lookup(const char *module, const char *signal, hwpin_t *out);
/* Iterate a module's generated pin bundle. Returns false when idx is past
   the end (or module unknown). sig/megapin buffers: >=48 and >=16 bytes. */
bool modmap_entry(const char *module, uint8_t idx,
                  char *sig, char *megapin, char *dir);
/* FLASH pointer to the bundle's module-name string for a RAM module
   string (for test_begin, whose args are flash). NULL if unknown. */
const char *modmap_name_P(const char *module);
/* Breakout-strip slot for a signal (slotmap_gen.h, generated by
   layout_gen.py from the netlist). 0 = this signal has no slot. */
uint8_t slot_of(const char *module, const char *signal);
void drv(const hwpin_t *p, bool level);
void rel(const hwpin_t *p);
bool smp(const hwpin_t *p);
bool floats(const hwpin_t *p);
void settle(void);
/* Poll a sampled pin until it reads `level` or timeout_ms elapses.
   The armed-watcher core for guided tests (button presses etc). */
bool await_level(const hwpin_t *p, bool level, uint16_t timeout_ms);
/* Release EVERY rig pin (all pinmap entries + the fixed-port buses) so a
   DUT board can be power-cycled without the rig backpowering it through
   input clamp diodes. Bumps g_pin_gen — module bind()s re-drive on the
   next run. */
void pins_idle(void);
extern uint8_t g_pin_gen;
/* Count rising edges on PD7 (Timer0 external clock pin T0) over gate_ms,
   gated by Timer1. Both timers restored to reset state afterwards.
   Caller must verify the signal actually lands on PD7. */
uint32_t freq_count_t0(uint16_t gate_ms);
void clk_bind(const hwpin_t *clk, const hwpin_t *clkn);
void clk_lo(void);
void clk_hi(void);
void step(void);

void bus_w_write(uint8_t v);
uint8_t bus_w_read(void);
void bus_w_release(void);
void bus_mdr_write(uint8_t v);
uint8_t bus_mdr_read(void);
void bus_mdr_release(void);
uint16_t bus_m_read(void);
void bus_m_drive(uint16_t v);
void bus_m_release(void);

/* module/name/label arguments are FLASH pointers (PSTR/PROGMEM) */
void test_begin(const char *module_P, const char *name_P);
void test_check_u16(uint16_t got, uint16_t want, const char *label_P);
void test_check_bool(bool got, bool want, const char *label_P);
void test_check_range(uint16_t got, uint16_t lo, uint16_t hi, const char *label_P);
/* RAM-label variants — runtime-built labels only */
void test_check_u16_r(uint16_t got, uint16_t want, const char *label);
void test_check_bool_r(bool got, bool want, const char *label);
bool test_end(void);
extern uint16_t g_pass, g_fail;

#endif
