/* GENERATED by docs/notes/progrom_gen.py — do not edit.
   Regenerate: python3 docs/notes/progrom_gen.py */
#ifndef PROGROM_EXPECT_H
#define PROGROM_EXPECT_H
#ifdef __AVR__
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif
#include <stdint.h>

#define PR_SIZE 32768u
#define PR_SAFE_FILL 0xFFu

/* burn signatures: byte 0 of each image */
#define PR_DIAG_BYTE0 0xA5u
#define PR_REAL_BYTE0 0x11u

/* CRC-16/CCITT-FALSE over all 32768 bytes */
#define PR_CRC_REAL 0xF501u
#define PR_CRC_DIAG 0xDFE7u

#define PR_DIAG_ZERO 0xA5u
#define PR_DIAG_WALK 0x40u

/* diag value is a pure function of its address — the rig computes
   it rather than carrying a 32KB table. Self-naming on 0 and 2^k. */
static inline uint8_t pr_diag_byte(uint16_t a) {
    a &= (uint16_t)(PR_SIZE - 1u);
    if (a == 0u) return PR_DIAG_ZERO;
    if ((a & (uint16_t)(a - 1u)) == 0u) {
        uint8_t k = 0;
        while ((uint16_t)(a >> k) > 1u) k++;
        return (uint8_t)(PR_DIAG_WALK | k);
    }
    return (uint8_t)(((uint16_t)(a * 0x9Du)) ^ (a >> 5));
}

/* the shipped program; every address at or past PR_PROGRAM_LEN
   reads PR_SAFE_FILL */
#define PR_PROGRAM_LEN 7u
static const uint8_t PR_PROGRAM[PR_PROGRAM_LEN] PROGMEM = {
    0x11, 0x05, 0x12, 0x03, 0x41, 0x51, 0xFF,
};

#define PR_EXPECT_SUM 0x08u   /* the milestone result */

#endif
