/* GENERATED by docs/notes/layout_gen.py — do not edit.
   Regenerate: python3 docs/notes/layout_gen.py <module> */
#ifndef SLOTMAP_GEN_H
#define SLOTMAP_GEN_H
#include <stdint.h>
#include <avr/pgmspace.h>

typedef struct { const char *signal; uint8_t slot; } slotsig_t;
typedef struct { const char *module; const slotsig_t *sig;
                 uint8_t n; } slotmap_t;

static const char sl_s0[] PROGMEM = "ALU_C";
static const char sl_s1[] PROGMEM = "ALU_CIN";
static const char sl_s2[] PROGMEM = "ALU_V";
static const char sl_s3[] PROGMEM = "CLK";
static const char sl_s4[] PROGMEM = "CRY";
static const char sl_s5[] PROGMEM = "CW10=SA1";
static const char sl_s6[] PROGMEM = "CW11=SA0";
static const char sl_s7[] PROGMEM = "CW9=SA2";
static const char sl_s8[] PROGMEM = "FLAG_C";
static const char sl_s9[] PROGMEM = "FLAG_N";
static const char sl_s10[] PROGMEM = "FLAG_V";
static const char sl_s11[] PROGMEM = "FLAG_Z";
static const char sl_s12[] PROGMEM = "LE_TMP_A";
static const char sl_s13[] PROGMEM = "LE_TMP_B";
static const char sl_s14[] PROGMEM = "W0";
static const char sl_s15[] PROGMEM = "W1";
static const char sl_s16[] PROGMEM = "W2";
static const char sl_s17[] PROGMEM = "W3";
static const char sl_s18[] PROGMEM = "W4";
static const char sl_s19[] PROGMEM = "W5";
static const char sl_s20[] PROGMEM = "W6";
static const char sl_s21[] PROGMEM = "W7";
static const char sl_s22[] PROGMEM = "Z";
static const char sl_s23[] PROGMEM = "~{ALU_OUT}";
static const char sl_s24[] PROGMEM = "~{CLK}";
static const char sl_s25[] PROGMEM = "~{REG_A_LOAD}";
static const char sl_s26[] PROGMEM = "~{REG_B_LOAD}";
static const char sl_s27[] PROGMEM = "~{RESET}";
static const char sl_s28[] PROGMEM = "alu";

static const slotsig_t slot_alu[] PROGMEM = {
    {sl_s0, 26},
    {sl_s1, 33},
    {sl_s2, 27},
    {sl_s3, 28},
    {sl_s4, 25},
    {sl_s5, 35},
    {sl_s6, 34},
    {sl_s7, 36},
    {sl_s8, 21},
    {sl_s9, 22},
    {sl_s10, 23},
    {sl_s11, 24},
    {sl_s12, 31},
    {sl_s13, 32},
    {sl_s14, 9},
    {sl_s15, 10},
    {sl_s16, 11},
    {sl_s17, 12},
    {sl_s18, 13},
    {sl_s19, 14},
    {sl_s20, 15},
    {sl_s21, 16},
    {sl_s22, 20},
    {sl_s23, 17},
    {sl_s24, 29},
    {sl_s25, 18},
    {sl_s26, 19},
    {sl_s27, 30}
};

static const slotmap_t SLOTMAPS[] PROGMEM = {
    {sl_s28, slot_alu, 28}
};
#define SLOTMAP_COUNT 1

#endif
